import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { MainPage } from '../components/MainPage';
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hao Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage />
    </>
  );
};

export default Home;
